"""add display numbers and lead notification tracking

Revision ID: 0db6aaa83c15
Revises: 16d5ebecf8e9
Create Date: 2026-09-02 00:41:01.783253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db6aaa83c15'
down_revision: Union[str, Sequence[str], None] = '16d5ebecf8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_sessions', sa.Column('standard_token_counter', sa.Integer(), nullable=False))
    op.add_column('queue_sessions', sa.Column('priority_token_counter', sa.Integer(), nullable=False))
    op.add_column('queue_sessions', sa.Column('emergency_token_counter', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('display_number', sa.String(length=10), nullable=True))
    op.add_column('tokens', sa.Column('lead_notified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'lead_notified')
    op.drop_column('tokens', 'display_number')
    op.drop_column('queue_sessions', 'emergency_token_counter')
    op.drop_column('queue_sessions', 'priority_token_counter')
    op.drop_column('queue_sessions', 'standard_token_counter')
    # ### end Alembic commands ###
