"""initial schema

Revision ID: 16d5ebecf8e9
Revises: 
Create Date: 2026-09-02 00:04:34.503294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16d5ebecf8e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('priority_fee_paise', sa.Integer(), nullable=False),
    sa.Column('standard_priority_ratio', sa.String(length=10), nullable=False),
    sa.Column('notify_lead_count', sa.SmallInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', postgresql.ENUM('receptionist', 'doctor', 'admin', name='staff_role'), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'contact')
    )
    op.create_index(op.f('ix_staff_accounts_clinic_id'), 'staff_accounts', ['clinic_id'], unique=False)
    op.create_table('queue_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'paused', 'closed', name='session_status'), nullable=False),
    sa.Column('call_counter', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'doctor_id', 'session_date')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_contact', sa.String(length=120), nullable=False),
    sa.Column('tier', postgresql.ENUM('standard', 'priority', name='token_tier'), nullable=False),
    sa.Column('emergency_override', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('waiting', 'called', 'served', 'requeued', 'cancelled', name='token_status'), nullable=False),
    sa.Column('sequence_no', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('swap_used', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['queue_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tokens_session_status', 'tokens', ['session_id', 'status'], unique=False)
    op.create_index('idx_tokens_session_tier_seq', 'tokens', ['session_id', 'tier', 'sequence_no'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('channel', postgresql.ENUM('telegram', 'email', name='notif_channel'), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'sent', 'delivered', 'failed', name='notif_status'), nullable=False),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_token_id'), 'notification_log', ['token_id'], unique=False)
    op.create_table('payments',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('fee_amount_paise', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collected_by'], ['staff_accounts.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('service_time_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds > 0'),
    sa.ForeignKeyConstraint(['session_id'], ['queue_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sts_session', 'service_time_samples', ['session_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sts_session', table_name='service_time_samples')
    op.drop_table('service_time_samples')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notification_log_token_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index('idx_tokens_session_tier_seq', table_name='tokens')
    op.drop_index('idx_tokens_session_status', table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('queue_sessions')
    op.drop_index(op.f('ix_staff_accounts_clinic_id'), table_name='staff_accounts')
    op.drop_table('staff_accounts')
    op.drop_table('clinics')
    # ### end Alembic commands ###
